Models/CanBoDiaPhuong.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CanBoDiaPhuong
    {
        public int id { get; set; }
        public string name { get; set; }
        public string chucvu { get; set; }
        public string gmap { get; set; }
        public string phoneno { get; set; }
        public int thuoccap { get; set; }
        public string note { get; set; }
        public int fk_id { get; set; }
    }
}

Controllers/CanBoDiaPhuongsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NiceHandles.Models;
using PagedList;

namespace NiceHandles.Controllers
{
    public class CanBoDiaPhuongsController : Controller
    {
        private NHModel db = new NHModel();

        // GET: CanBoDiaPhuongs
        public ActionResult Index(string Search_Data, int? address_id, string Filter_Value)
        {
            address_id = address_id ?? db.Addresses.First().id;
            ViewBag.XA = address_id;
            if (Search_Data == null)
            {
                Search_Data = Filter_Value;
            }
            ViewBag.FilterValue = Search_Data;
            ViewBag.address_id = address_id;

            vCanBoDiaPhuongC1[] results = (from vcb in db.vCanBoDiaPhuongC1
                                           where (
                                           (vcb.name.ToUpper().Contains(!String.IsNullOrEmpty(Search_Data) ? Search_Data.ToUpper() : vcb.name.ToUpper())) &&
                                           vcb.address_id == (address_id.HasValue ? address_id.Value : vcb.address_id)
                                           )
                                           orderby vcb.name
                                           select vcb).ToArray();

            int Size_Of_Page = 200;
            int No_Of_Page = 1;
            return View(results.ToPagedList(No_Of_Page, Size_Of_Page));
        }

        // GET: CanBoDiaPhuongs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CanBoDiaPhuong canBoDiaPhuong = db.CanBoDiaPhuongs.Find(id);
            if (canBoDiaPhuong == null)
            {
                return HttpNotFound();
            }
            return View(canBoDiaPhuong);
        }

        // GET: CanBoDiaPhuongs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CanBoDiaPhuongs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,chucvu,gmap,phoneno,thuoccap,note,fk_id")] CanBoDiaPhuong canBoDiaPhuong)
        {
            if (ModelState.IsValid)
            {
                db.CanBoDiaPhuongs.Add(canBoDiaPhuong);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(canBoDiaPhuong);
        }

        // GET: CanBoDiaPhuongs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CanBoDiaPhuong canBoDiaPhuong = db.CanBoDiaPhuongs.Find(id);
            if (canBoDiaPhuong == null)
            {
                return HttpNotFound();
            }
            ViewBag.CAPXA = canBoDiaPhuong.thuoccap == (int)XModels.eThuocCap.cap2 ? canBoDiaPhuong.fk_id : db.DvhcC1.Single(x => x.id == canBoDiaPhuong.fk_id).address_id;
            if (canBoDiaPhuong.thuoccap == (int)XModels.eThuocCap.cap1) ViewBag.CAPTHON = canBoDiaPhuong.fk_id;
            return View(canBoDiaPhuong);
        }

        // POST: CanBoDiaPhuongs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,chucvu,gmap,phoneno,thuoccap,note,fk_id")] CanBoDiaPhuong canBoDiaPhuong)
        {
            if (ModelState.IsValid)
            {
                db.Entry(canBoDiaPhuong).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CAPXA = canBoDiaPhuong.thuoccap == (int)XModels.eThuocCap.cap2 ? canBoDiaPhuong.fk_id : db.DvhcC1.Single(x => x.address_id == canBoDiaPhuong.fk_id).address_id;
            if (canBoDiaPhuong.thuoccap == (int)XModels.eThuocCap.cap1) ViewBag.CAPTHON = canBoDiaPhuong.fk_id;
            return View(canBoDiaPhuong);
        }

        // GET: CanBoDiaPhuongs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CanBoDiaPhuong canBoDiaPhuong = db.CanBoDiaPhuongs.Find(id);
            if (canBoDiaPhuong == null)
            {
                return HttpNotFound();
            }
            return View(canBoDiaPhuong);
        }

        // POST: CanBoDiaPhuongs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CanBoDiaPhuong canBoDiaPhuong = db.CanBoDiaPhuongs.Find(id);
            db.CanBoDiaPhuongs.Remove(canBoDiaPhuong);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public JsonResult GetThon(int xa)
        {
            var lst = db.DvhcC1.Where(c => c.address_id == xa);
            return Json(lst, JsonRequestBehavior.AllowGet);
        }
    }
}

Views/CanBoDiaPhuongs/Create.cshtml
@model NiceHandles.Models.CanBoDiaPhuong
@using NiceHandles.Models
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var db = new NHModel();
}

<h2>Thêm mới</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Cán bộ địa phương</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.Label("Đơn vị hành chính cấp", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.thuoccap, new SelectList(XModels.sThuocCap, "Key", "Value"), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.HiddenFor(model => model.fk_id)
        <div class="form-group">
            @Html.Label("Xã", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("capxa", new SelectList(db.Addresses.Select(x => new { id = x.id, name = x.name }), "id", "name", ViewBag.CAPXA), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.fk_id, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Thôn", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("capthon", new SelectList(db.DvhcC1.Select(x => new { id = x.id, name = x.name }), "id", "name", ViewBag.CAPTHON), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.fk_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Họ tên", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Chức vụ", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.chucvu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.chucvu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Địa chỉ GMap", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.gmap, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.gmap, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Số điện thoại", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phoneno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phoneno, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Ghi chú", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm mới" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Về danh sách", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $("#thuoccap").change(function () {
                var thuoccap = $(this).val();
                if (thuoccap == 0) {
                    $("#capthon").prop("disabled", false);
                } else {
                    $("#capthon").prop("disabled", true);
                }
            });
            $("#thuoccap").trigger("change");
            $("#capxa").change(function () {
                $.ajax({
                    url: '/CanBoDiaPhuongs/GetThon',
                    type: "GET",
                    dataType: "JSON",
                    data: { xa: $(this).val() },
                    success: function (thons) {
                        $("#capthon").html(""); // clear before appending new list
                        $.each(thons, function (i, thon) {
                            $("#capthon").append(
                                $('<option></option>').val(thon.id).html(thon.name));
                        });
                    }
                });
            });
            $("#capxa").trigger("change");
            $('form').submit(function (e) {
                var thuoccap = $("#thuoccap").val();
                if (thuoccap == 0) {
                    $("#fk_id").val($("#capthon").val());
                } else {
                    $("#fk_id").val($("#capxa").val());
                }
                this.submit();
            });
        });
    </script>
}

Views/CanBoDiaPhuongs/Delete.cshtml
@model NiceHandles.Models.CanBoDiaPhuong

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CanBoDiaPhuong</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.chucvu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.chucvu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gmap)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gmap)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phoneno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phoneno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.thuoccap)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.thuoccap)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.note)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fk_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fk_id)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/CanBoDiaPhuongs/Details.cshtml
@model NiceHandles.Models.CanBoDiaPhuong

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>CanBoDiaPhuong</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.chucvu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.chucvu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gmap)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gmap)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phoneno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phoneno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.thuoccap)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.thuoccap)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.note)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fk_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fk_id)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/CanBoDiaPhuongs/Edit.cshtml
@model NiceHandles.Models.CanBoDiaPhuong
@using NiceHandles.Models
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var db = new NHModel();
    int CAPTHON = ViewBag.CAPTHON != null ? (int)ViewBag.CAPTHON : -1;
}

<h2>Chỉnh sửa</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Cán bộ địa phương</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.Label("Đơn vị hành chính cấp", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.thuoccap, new SelectList(XModels.sThuocCap, "Key", "Value"), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.HiddenFor(model => model.fk_id)
        <div class="form-group">
            @Html.Label("Xã", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("capxa", new SelectList(db.Addresses.Select(x => new { id = x.id, name = x.name }), "id", "name", ViewBag.CAPXA), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.fk_id, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.Hidden("hdfCAPTHON", CAPTHON)
        <div class="form-group">
            @Html.Label("Thôn", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("capthon", new SelectList(db.DvhcC1.Select(x => new { id = x.id, name = x.name }), "id", "name", ViewBag.CAPTHON), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.fk_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Họ tên", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Chức vụ", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.chucvu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.chucvu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Địa chỉ GMap", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.gmap, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.gmap, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Số điện thoại", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phoneno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phoneno, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Ghi chú", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu lại" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Về danh sách", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $("#thuoccap").change(function () {
                var thuoccap = $(this).val();
                if (thuoccap == 0) {
                    $("#capthon").prop("disabled", false);
                } else {
                    $("#capthon").prop("disabled", true);
                }
            });
            $("#thuoccap").trigger("change");
            $("#capxa").change(function () {
                $.ajax({
                    url: '/CanBoDiaPhuongs/GetThon',
                    type: "GET",
                    dataType: "JSON",
                    data: { xa: $(this).val() },
                    success: function (thons) {
                        $("#capthon").html(""); // clear before appending new list
                        $.each(thons, function (i, thon) {
                            $("#capthon").append(
                                $('<option></option>').val(thon.id).html(thon.name));
                        });
                        $("#capthon").val($("#hdfCAPTHON").val()).trigger("change");
                    }
                });
            });
            $("#capxa").trigger("change");

            $('form').submit(function (e) {
                var thuoccap = $("#thuoccap").val();
                if (thuoccap == 0) {
                    $("#fk_id").val($("#capthon").val());
                } else {
                    $("#fk_id").val($("#capxa").val());
                }
                this.submit();
            });
        });
    </script>
}

Views/CanBoDiaPhuongs/Index.cshtml
@model PagedList.IPagedList<NiceHandles.Models.vCanBoDiaPhuongC1>
@using PagedList.Mvc;
@using NiceHandles.Models
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var db = new NHModel();
    int XA = Convert.ToInt32(ViewBag.XA);
    var c2s = db.CanBoDiaPhuongs.Where(x => x.fk_id == XA && x.thuoccap == (int)XModels.eThuocCap.cap2);
}

<h2>Danh sách cán bộ địa phương</h2>

<p>
    @Html.ActionLink("Thêm mới", "Create")
</p>

@using (Html.BeginForm("Index", "CanBoDiaPhuongs", FormMethod.Get))
{
    <div class="row">
        <div class="col-sm-2">
            <div class="form-group">
                @Html.TextBox("Search_Data", ViewBag.FilterValue as string, new { @class = "form-control", placeholder = "Tìm kiếm" })
            </div>
        </div>
        <div class="col-sm-2">
            <div class="form-group">
                @Html.DropDownList("address_id", new SelectList(db.Addresses, "id", "name", ViewBag.XA), "Chọn xã", new { @class = "form-control" })
            </div>
        </div>
        <div class="col-lg-2 col-sm-2 ">
            <div class="form-group">
                <button type="submit" class="btn btn-primary" style="height: 28px; width: 100px;">Tìm kiếm</button>
            </div>
        </div>
    </div>
}

<h4>CÁN BỘ CẤP XÃ/PHƯỜNG</h4>
<table class="table">
    <tr>
        <th>
            Tên
        </th>
        <th>
            Chức vụ
        </th>
        <th>
            Gmap
        </th>
        <th>
            Số điện thoại
        </th>
        <th>
            Ghi chú
        </th>
        <th></th>
    </tr>

    @foreach (var item in c2s)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.chucvu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.gmap)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.phoneno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.note)
            </td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.id }) |
                @Html.ActionLink("Xóa", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>

<h4>CÁN BỘ CẤP TỔ/THÔN</h4>

<table class="table">
    <tr>
        <th>
            Họ tên
        </th>
        <th>
            Chức vụ
        </th>
        <th>
            Gmap
        </th>
        <th>
            Số điện thoại
        </th>
        <th>
            Ghi chú
        </th>
        <th>
            Thôn
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.chucvu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.gmap)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.phoneno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.note)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DvhcName)
            </td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.id }) |
                @Html.ActionLink("Xóa", "Delete", new { id = item.id })
            </td>
        </tr>
    }
</table>