Models/InOutChoDuyet.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InOutChoDuyet
    {
        public int id { get; set; }
        public string code { get; set; }
        public string note { get; set; }
        public System.DateTime time { get; set; }
        public int status { get; set; }
    }
}

Controllers/InOutChoDuyetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Diagnostics.Contracts;
using System.IO;
using System.Linq;
using System.Net;
using System.Runtime.Remoting.Metadata.W3cXsd2001;
using System.Web;
using System.Web.Mvc;
using Aspose.Words;
using Aspose.Words.Rendering;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using NiceHandles.Models;
using PagedList;
using static System.Data.Entity.Infrastructure.Design.Executor;
using static NiceHandles.Controllers.InOutsController;
using static NiceHandles.Models.XModels;

namespace NiceHandles.Controllers
{
    public class InOutChoDuyetsController : Controller
    {
        private NHModel db = new NHModel();

        // GET: InOutChoDuyets
        [Authorize(Roles = "SuperAdmin,Manager,Accounting")]
        public ActionResult Index(string Search_Data, string Filter_Value, int? Page_No, string fromdate, string todate)
        {
            if (Search_Data != null)
            {
                Page_No = 1;
            }
            else
            {
                Search_Data = Filter_Value;
            }
            ViewBag.FilterValue = Search_Data;

            ViewBag.FROMDATE = fromdate;
            ViewBag.TODATE = todate;
            DateTime FromDate = string.IsNullOrEmpty(fromdate) ? new DateTime() : DateTime.Parse(fromdate);
            DateTime ToDate = string.IsNullOrEmpty(todate) ? DateTime.Now : DateTime.Parse(todate);
            ToDate = ToDate.AddDays(1);

            var results = from v in db.InOutChoDuyets
                          where (
                          (string.IsNullOrEmpty(v.note) ||
                          v.note.ToUpper().Contains(!String.IsNullOrEmpty(Search_Data) ? Search_Data.ToUpper() : v.note.ToUpper()) ||
                          v.code.ToUpper().Contains(!String.IsNullOrEmpty(Search_Data) ? Search_Data.ToUpper() : v.code.ToUpper())
                          ) &&
                          v.time >= FromDate &&
                          v.time < ToDate
                          )
                          orderby v.time descending
                          select v;

            int Size_Of_Page = 30;
            int No_Of_Page = (Page_No ?? 1);
            return View(results.ToPagedList(No_Of_Page, Size_Of_Page));
        }

        [Authorize(Roles = "SuperAdmin,Manager,Accounting")]
        public ActionResult ChoDuyet(string Search_Data, int? s_account_id, int? s_type, int? s_category_id, int? s_currency, string fromdate, string todate)
        {
            ViewBag.FilterValue = Search_Data;
            ViewBag.category_id = s_category_id;
            ViewBag.account_id = s_account_id;

            ViewBag.FROMDATE = fromdate;
            ViewBag.TODATE = todate;
            DateTime FromDate = string.IsNullOrEmpty(fromdate) ? new DateTime() : DateTime.Parse(fromdate);
            DateTime ToDate = string.IsNullOrEmpty(todate) ? DateTime.Now : DateTime.Parse(todate);
            ToDate = ToDate.AddDays(1);
            ViewBag.type = s_type;

            var results = from v in db.InOuts
                          where (
                          (string.IsNullOrEmpty(v.note) || v.note.ToUpper().Contains(!String.IsNullOrEmpty(Search_Data) ? Search_Data.ToUpper() : v.note.ToUpper())) &&
                          v.category_id == (s_category_id.HasValue ? s_category_id.Value : v.category_id) &&
                          v.type == (s_type.HasValue ? s_type.Value : v.type) &&
                          v.account_id == (s_account_id.HasValue ? s_account_id.Value : v.account_id) &&
                          v.currency == (s_currency.HasValue ? s_currency.Value : v.currency) &&
                          v.status < (int)XInOut.eStatus.DaThucHien &&
                          v.time >= FromDate &&
                          v.time < ToDate
                          )
                          orderby v.time descending
                          select v;
            return View(results);
        }
        [Authorize(Roles = "SuperAdmin,Manager,Accounting")]
        public ActionResult DuyetTheoHoSo()
        {
            var results = from v in db.InOuts
                          where (
                          v.status == (int)XInOut.eStatus.ChoDuyet
                          )
                          orderby v.time descending
                          select v;
            return View(results);
        }
        [Authorize(Roles = "SuperAdmin")]
        public ActionResult ChoXemXet(string Search_Data, int? s_account_id, int? s_type, int? s_category_id, int? s_currency, string fromdate, string todate)
        {
            ViewBag.FilterValue = Search_Data;
            ViewBag.category_id = s_category_id;
            ViewBag.account_id = s_account_id;

            ViewBag.FROMDATE = fromdate;
            ViewBag.TODATE = todate;
            DateTime FromDate = string.IsNullOrEmpty(fromdate) ? new DateTime() : DateTime.Parse(fromdate);
            DateTime ToDate = string.IsNullOrEmpty(todate) ? DateTime.Now : DateTime.Parse(todate);
            ToDate = ToDate.AddDays(1);
            ViewBag.type = s_type;

            var results = from v in db.InOuts
                          where (
                          (string.IsNullOrEmpty(v.note) || v.note.ToUpper().Contains(!String.IsNullOrEmpty(Search_Data) ? Search_Data.ToUpper() : v.note.ToUpper())) &&
                          v.category_id == (s_category_id.HasValue ? s_category_id.Value : v.category_id) &&
                          v.type == (s_type.HasValue ? s_type.Value : v.type) &&
                          v.account_id == (s_account_id.HasValue ? s_account_id.Value : v.account_id) &&
                          v.currency == (s_currency.HasValue ? s_currency.Value : v.currency) &&
                          v.status < (int)XInOut.eStatus.DaThucHien &&
                          v.unlock == 1 &&
                          v.time >= FromDate &&
                          v.time < ToDate
                          )
                          orderby v.time descending
                          select v;
            return View(results);
        }

        // GET: InOutChoDuyets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InOutChoDuyet inOutChoDuyet = db.InOutChoDuyets.Find(id);
            if (inOutChoDuyet == null)
            {
                return HttpNotFound();
            }
            return View(inOutChoDuyet);
        }

        // GET: InOutChoDuyets/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: InOutChoDuyets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(InOutChoDuyet inOutChoDuyet, string checkedids)
        {
            inOutChoDuyet.time = DateTime.Now;
            inOutChoDuyet.status = (int)XInOutChoDuyet.eStatus.Processing;
            db.InOutChoDuyets.Add(inOutChoDuyet);
            db.SaveChanges();

            var ioids = checkedids.Split(new string[] { "," }, StringSplitOptions.RemoveEmptyEntries);
            ioids = ioids.Select(x => x.Replace("io", "")).ToArray();
            foreach (var item in ioids)
            {
                var io = db.InOuts.Find(Convert.ToInt64(item));
                io.inoutchoduyet_id = inOutChoDuyet.id;
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Details(InOutChoDuyet inOutChoDuyet, string checkedids)
        {
            if (inOutChoDuyet.status == (int)XInOutChoDuyet.eStatus.Processing)
            {
                inOutChoDuyet.time = DateTime.Now;
                inOutChoDuyet.status = (int)XInOutChoDuyet.eStatus.Complete;

                var ioids = checkedids.Split(new string[] { "," }, StringSplitOptions.RemoveEmptyEntries);
                ioids = ioids.Select(x => x.Replace("io", "")).ToArray();
                var lstioids = ioids.Select(x => Convert.ToInt64(x)).ToArray();
                var lstInOuts = db.InOuts.Where(x => x.inoutchoduyet_id == inOutChoDuyet.id).ToArray();
                foreach (var io in lstInOuts)
                {
                    if (!lstioids.Contains(io.id))
                    {
                        io.inoutchoduyet_id = null;
                    }
                }
                db.SaveChanges();
            }
            return View(inOutChoDuyet);
        }
        public ActionResult Action(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InOutChoDuyet inOutChoDuyet = db.InOutChoDuyets.Find(id);
            if (inOutChoDuyet == null)
            {
                return HttpNotFound();
            }
            return View(inOutChoDuyet);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Action(InOutChoDuyet inOutChoDuyet, string checkedids)
        {
            inOutChoDuyet.time = DateTime.Now;
            var ioids = checkedids.Split(new string[] { "," }, StringSplitOptions.RemoveEmptyEntries);
            ioids = ioids.Select(x => x.Replace("io", "")).ToArray();
            var lstioids = ioids.Select(x => Convert.ToInt64(x)).ToArray();
            var lstInOuts = db.InOuts.Where(x => x.inoutchoduyet_id == inOutChoDuyet.id).ToArray();

            if (inOutChoDuyet.status == (int)XInOutChoDuyet.eStatus.Processing)
            {
                foreach (var io in lstInOuts)
                {

Views/InOutChoDuyets/Action.cshtml
@model NiceHandles.Models.InOutChoDuyet
@using NiceHandles.Models;
@{
    Layout = "~/Views/Shared/_LayoutEmpty.cshtml";
    ViewBag.Title = "Duyệt";
    var db = new NHModel();
    var lstDuyet = db.InOuts.Where(x => x.inoutchoduyet_id == Model.id);
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.id)
    @Html.HiddenFor(model => model.time)
    @Html.HiddenFor(model => model.status)
    <div class="row" style="margin: 0 0 15px;">
        @Html.LabelFor(model => model.note, "Ghi chú", htmlAttributes: new { @class = "control-label col-md-1" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.note, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.note, "", new { @class = "text-danger" })
        </div>
    </div>
    <table class="table">
        <tr>
            <th style="width: 20px;"><input type="checkbox" checked id="cboAll" /></th>
            <th>
                Hợp đồng
            </th>
            <th>
                Người thực hiện
            </th>
            <th>
                Loại
            </th>
            <th>
                Số tiền
            </th>
            <th>
                Ghi chú
            </th>
        </tr>

        @foreach (var item in lstDuyet)
        {
            var acc = db.Accounts.Find(item.account_id);
            var cate = db.Categories.Find(item.category_id);
            var contract_name = string.Empty;
            if (item.contract_id.HasValue)
            {
                contract_name = db.Contracts.Find(item.contract_id).name;
            }
            <tr>
                <td>
                    <input type="checkbox" checked id="io@(item.id)" />
                </td>
                <td>
                    @contract_name
                </td>
                <td>
                    @acc.fullname
                </td>
                <td>
                    @cate.name
                </td>
                <td>
                    @item.amount.ToString("N0")
                </td>
                <td>
                    @item.note
                </td>
            </tr>
        }
    </table>

    <div class="col-md-offset-2 col-md-10">
        @if (Model.status == (int)XInOutChoDuyet.eStatus.Processing)
        {
            <input type="submit" value="Thực hiện" onclick="setCheckedIds();" class="btn btn-success" />
        }
        <input type="button" onclick="Print(@Model.id)" value=" Bản in" class="btn btn-default" />
    </div>
    @Html.Hidden("checkedids")
}
<iframe id="my_iframe" style="display:none;"></iframe>
<style>
    body {
        padding-top: 10px;
    }
</style>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $("#cboAll").click(function () {
                $('.table input:checkbox').not(this).prop('checked', this.checked);
            });
        });
        function setCheckedIds() {
            var lst = "";
            $("td input:checked").each(function () {
                lst += $(this).attr("id") + ",";
            });
            $("#checkedids").val(lst);
            var koduyet = $("td input:checkbox:not(:checked)").length;
        }
        function Print(id) {
            $.ajax({
                url: '/InoutChoDuyets/InOutChoDuyetPrint',
                data: {
                    id: id
                },
                type: "GET",
                dataType: "JSON",
                success: function (url) {
                    document.getElementById('my_iframe').src = url;
                }
            });
        }
    </script>
}

Views/InOutChoDuyets/Create.cshtml
@model NiceHandles.Models.InOutChoDuyet
@using NiceHandles.Models;
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var db = new NHModel();
    var lstDuyet = db.InOuts.Where(x => x.status == (int)XInOut.eStatus.DaDuyet && !x.inoutchoduyet_id.HasValue);
}

<h2>Danh sách chờ thực hiện</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Thu chi</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-2">
                <input type="submit" value="Thực hiện" onclick="setCheckedIds();" class="btn btn-primary" />
            </div>
            @Html.LabelFor(model => model.note, "Ghi chú", htmlAttributes: new { @class = "control-label col-md-1" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.note, "", new { @class = "text-danger" })
            </div>
        </div>
        <table class="table">
            <tr>
                <th style="width: 20px;"><input type="checkbox" id="cboAll" /></th>
                <th>
                    Người thực hiện
                </th>
                <th>
                    Loại
                </th>
                <th>
                    Số tiền
                </th>
                <th>
                    Ghi chú
                </th>
            </tr>

            @foreach (var item in lstDuyet)
            {
                var acc = db.Accounts.Find(item.account_id);
                var cate = db.Categories.Find(item.category_id);
                <tr>
                    <td>
                        <input type="checkbox" id="io@(item.id)" />
                    </td>
                    <td>
                        @acc.fullname
                    </td>
                    <td>
                        @cate.name
                    </td>
                    <td>
                        @item.amount.ToString("N0")
                    </td>
                    <td>
                        @item.note
                    </td>
                </tr>
            }
        </table>
    </div>
    @Html.Hidden("checkedids")
}

<div>
    @Html.ActionLink("Về danh sách", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $("#cboAll").click(function () {
                $('.table input:checkbox').not(this).prop('checked', this.checked);
            });
        });
        function setCheckedIds() {
            var lst = "";
            $("td input:checked").each(function () {
                lst += $(this).attr("id") + ",";
            });
            $("#checkedids").val(lst);
        }
    </script>
}

Views/InOutChoDuyets/Index.cshtml
@model PagedList.IPagedList<NiceHandles.Models.InOutChoDuyet>
@using PagedList.Mvc;
@using NiceHandles.Models
@using Microsoft.AspNet.Identity;

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutEmpty.cshtml";
}
<div style="padding: 10px; background-color: lavenderblush;">
    <h4 class="fa fa-list"> DANH SÁCH PHIẾU CHI</h4>
    @using (Html.BeginForm("Index", "InOutChoDuyets", FormMethod.Get))
    {
        <div class="row">
            <div class="col-sm-1">
                <div class="form-group">
                    @Html.TextBox("fromdate", ViewBag.FROMDATE as string, new { @class = "form-control datetime", placeholder = "Từ ngày", autocomplete = "off" })
                </div>
            </div>
            <div class="col-sm-1">
                <div class="form-group">
                    @Html.TextBox("todate", ViewBag.TODATE as string, new { @class = "form-control datetime", placeholder = "Đến ngày", autocomplete = "off" })
                </div>
            </div>
            <div class="col-sm-1">
                <div class="form-group">
                    @Html.TextBox("Search_Data", ViewBag.FilterValue as string, new { @class = "form-control", placeholder = "Tìm kiếm" })
                </div>
            </div>
            <div class="col-sm-2">
                <div class="form-group">
                    <button type="submit" class="btn btn-info" style="height: 32px; width: 100px;"><i class="fa fa-search"></i> Tìm kiếm</button>
                </div>
            </div>
        </div>
    }
    <table class="table table-hover">
        <thead>
            <tr>
                <th>
                    Thời gian
                </th>
                <th>
                    Mã
                </th>
                <th>
                    Ghi chú
                </th>
                <th>
                </th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.Count; i++)
            {
                string contract_name = string.Empty;
                <tr>
                    <td>@Model[i].time.ToString("dd/MM/yyyy")</td>
                    <td>@Model[i].code</td>
                    <td>@Model[i].note</td>
                    <td>
                        <button onclick="Print(@(Model[i].id));" class="btn btn-default">Bản in</button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    @if (Model.PageCount > 1)
    {
        <div class="row" style="margin-top: 10px;">
            <div class="col-sm-1">
                Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
            </div>
            <div class="col-sm-10">
                @Html.PagedListPager(Model, Page_No => Url.Action("Index", new { Page_No, Filter_Value = ViewBag.FilterValue, fromdate = ViewBag.FROMDATE, todate = ViewBag.TODATE }))
            </div>
        </div>
    }
    <iframe id="my_iframe" style="display:none;"></iframe>
</div>
<style>
    body {
        width: 97%;
        padding-top: 0;
        background-color: lavenderblush;
    }
</style>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        var currentDelCtr = null;
        $(document).ready(function () {
            $(".datetime").datepicker({
                "autoclose": true,
                "todayHighlight": true,
                "dateFormat": "dd/mm/yyyy",
                "format": "dd/mm/yyyy",
            }).datepicker();
        });
        function Print(id) {
            $.ajax({
                url: '/InoutChoDuyets/InOutChoDuyetPrint',
                data: {
                    id: id
                },
                type: "GET",
                dataType: "JSON",
                success: function (url) {
                    document.getElementById('my_iframe').src = url;
                }
            });
        }
    </script>
}

Views/InOutChoDuyets/TheoDoiChiBak.cshtml
@model PagedList.IPagedList<NiceHandles.Models.vTheoDoiChi>
@using PagedList.Mvc;
@using NiceHandles.Models
@{
    var db = new NHModel();
}

<h3> DANH SÁCH CÁC KHOẢN CHI ĐI THỰC HIỆN</h3>
@using (Html.BeginForm("TheoDoiChi", "InOutChoDuyets", FormMethod.Get))
{
    <div class="row">
        <div class="col-sm-1">
            <div class="form-group">
                @Html.TextBox("fromdate", ViewBag.FROMDATE as string, new { @class = "form-control datetime", placeholder = "Từ ngày", autocomplete = "off" })
            </div>
        </div>
        <div class="col-sm-1">
            <div class="form-group">
                @Html.TextBox("todate", ViewBag.TODATE as string, new { @class = "form-control datetime", placeholder = "Đến ngày", autocomplete = "off" })
            </div>
        </div>
        <div class="col-sm-1">
            <div class="form-group">
                @Html.DropDownList("account_id", new SelectList(db.Accounts.Where(x => x.sta == (int)XAccount.eStatus.Processing), "id", "fullname"), "Tài khoản", new { @class = "form-control" })
            </div>
        </div>
        <div class="col-sm-1">
            <div class="form-group">
                @Html.DropDownList("status", new SelectList(XDuChiNhatKy.sStatus, "Key", "Value"), "Trạng thái", new { @class = "form-control" })
            </div>
        </div>
        <div class="col-sm-2">
            <div class="form-group">
                @Html.DropDownList("contract_id", new SelectList(new Contract[] { }, "contract_id", "name"), "Chọn hợp đồng", new { @class = "form-control" })
            </div>
        </div>
        <div class="col-sm-1">
            <div class="form-group">
                @Html.TextBox("Search_Data", ViewBag.FilterValue as string, new { @class = "form-control", placeholder = "Tìm kiếm" })
            </div>
        </div>
        <div class="col-sm-2">
            <div class="form-group">
                <button type="submit" class="btn btn-primary" style="height: 32px; width: 100px;"><i class="fa fa-search"></i> Tìm kiếm</button>
                <button type="button" style="margin-left: 15px;" class="btn btn-default" onclick="Print();"><i class="fa fa-print"></i> Bản in</button>
            </div>
        </div>
    </div>
}
<div style="border-radius: 10px; background-color: aliceblue; padding: 15px;" class="row">
    <div class="col-sm-2">Tổng: <b> @ViewBag.TONG </b></div>
    <div class="col-sm-2 text-primary">Lương đang giữ: <b>@ViewBag.SumLuongGiu </b></div>
    <div class="col-sm-2 text-danger">Chờ thực hiện: <b>@ViewBag.SumChoThuHien </b></div>
    <div class="col-sm-2 text-primary">Đã thực hiện: <b>@ViewBag.SumDaThucHien </b></div>
    <div class="col-sm-2 text-muted">Tiền trả lại: <b>@ViewBag.SumTraLai </b></div>
</div>
<hr />
<div class="row" id="duyetchi">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>
                    Hợp đồng
                </th>
                <th>
                    Địa chỉ
                </th>
                <th>
                    Dịch vụ
                </th>
                <th>
                    Người lĩnh/TH
                </th>
                <th>
                    Loại chi tiết
                </th>
                <th>
                    Số tiền
                </th>
                <th>
                    Tiến độ
                </th>
                <th>
                    Ghi chú
                </th>
                <th>
                    Trả lại
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td style="line-height: 30px;">
                        @item.contract_name
                    </td>
                    <td style="line-height: 30px;">
                        @item.address_name
                    </td>
                    <td style="line-height: 30px;">
                        @item.service_name
                    </td>
                    <td style="line-height: 30px;">
                        @item.fullname
                    </td>
                    <td style="line-height: 30px;">
                        @item.category_name
                    </td>
                    <td style="line-height: 30px;">
                        @item.amount.ToString("N0")
                    </td>
                    <td>
                        @if (item.status < (int)XDuChiNhatKy.eStatus.DaDi)
                        {
                            <button class="btn btn-info" type="button" onclick="ConfirmDialog(@item.inout_id, @(item.status + 1), null,'Xác nhận thực hiện');"> @XDuChiNhatKy.sStatus[item.status]</button>
                        }
                        else
                        {
                            @XDuChiNhatKy.sStatus[item.status]
                        }
                    </td>
                    <td>
                        <input type="text" value="@item.note" class="form-control" onchange="ConfirmDialog(@item.inout_id, null, this.value,'Xác nhận thực hiện');" />
                    </td>
                    <td>
                        <button class="btn btn-danger" type="button" onclick="ConfirmTraLai(@item.inout_id,'Xác nhận thực hiện');">@XDuChiNhatKy.sStatus[(int)XDuChiNhatKy.eStatus.TraLai]</button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    @if (Model.PageCount > 1)
    {
        <div class="row" style="margin-top: 10px;">
            <div class="col-sm-1">
                Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
            </div>
            <div class="col-sm-10">
                @Html.PagedListPager(Model, Page_No => Url.Action("TheoDoiChi", new { Page_No, Filter_Value = ViewBag.FilterValue, account_id = ViewBag.account_id, category_id = ViewBag.category_id, contract_id = ViewBag.contract_id, status = ViewBag.status, fromdate = ViewBag.FROMDATE, todate = ViewBag.TODATE }))
            </div>
        </div>
    }
</div>
<iframe id="my_iframe" style="display:none;"></iframe>
<style>
    .select2 .selection .select2-selection {
        height: 34px;
    }
</style>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <link href="~/Content/jquery-confirm.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-confirm.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            SetSelect2("#contract_id", "/Jobs/GetContract", "VD: Nguyễn Văn A");
        });
        function DiThucHien(id, status, note) {
            $.ajax({
                url: '/DuChis/DiThucHien',
                data: {
                    id: id,
                    status: status,
                    note: note
                },
                type: "POST",
                dataType: "JSON",
                success: function (nhatky) {
                    if (note) {
                        toastr.success("Đã lưu thành công", "Ghi chú thực hiện", { timeOut: 5000 });
                    } else {
                        document.location.reload();
                    }
                }
            });
        }
        function TraLaiDuChi(id) {
            $.ajax({
                url: '/DuChis/TraLaiDuChi',
                data: {
                    id: id
                },
                type: "POST",
                dataType: "JSON",
                success: function (obj) {
                    document.location.reload();
                }
            });
        }
        function Print() {
            var Search_Data = $("#Search_Data").val();
            var account_id = $("#account_id").val();
            var status = $("#status").val();
            var contract_id = $("#contract_id").val();
            var fromdate = $("#fromdate").val();
            var todate = $("#todate").val();

            $.ajax({
                url: '/InoutChoDuyets/BanInTheoDoiChi',
                data: {
                    Search_Data: Search_Data,
                    account_id: account_id,
                    status: status,
                    contract_id: contract_id,
                    fromdate: fromdate,
                    todate: todate
                },
                type: "GET",
                dataType: "JSON",
                success: function (url) {
                    document.getElementById('my_iframe').src = url;
                }
            });
        }
        function ConfirmDialog(id, status, note, message) {
            $.confirm({
                title: 'YÊU CẦU',
                content: message,
                buttons: {
                    confirm: {
                        text: 'Đồng ý',
                        action: function () {
                            DiThucHien(id, status, note);
                        }
                    },
                    cancel: function () {
                        // do nothing
                    }
                    //,somethingElse: {
                    //    text: 'Something else',
                    //    btnClass: 'btn-blue',
                    //    keys: ['enter', 'shift'],
                    //    action: function () {
                    //        $.alert('Something else?');
                    //    }
                    //}
                }
            });
        }
        function ConfirmTraLai(id, message) {
            $.confirm({
                title: 'YÊU CẦU',
                content: message,
                buttons: {
                    confirm: {
                        text: 'Đồng ý',
                        action: function () {
                            TraLaiDuChi(id);
                        }
                    },
                    cancel: function () {
                        // do nothing
                    }
                }
            });
        }
    </script>
}