Models/TreoPhuon.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreoPhuon
    {
        public int id { get; set; }
        public string Images { get; set; }
        public int DvhcC1_id { get; set; }
        public string GoogleMap { get; set; }
        public System.DateTime NgayTreo { get; set; }
        public Nullable<System.DateTime> NgayKiemTra { get; set; }
        public string note { get; set; }
    }
}

Controllers/TreoPhuonsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics.Contracts;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NiceHandles.Models;
using PagedList;
using static System.Data.Entity.Infrastructure.Design.Executor;

namespace NiceHandles.Controllers
{
    [Authorize(Roles = "SuperAdmin,Manager,Member,OutSide")]
    public class TreoPhuonsController : Controller
    {
        private NHModel db = new NHModel();

        // GET: TreoPhuons
        public ActionResult Index(int? Page_No, int? Add, string fromdate, string todate)
        {
            ViewBag.FROMDATE = fromdate;
            ViewBag.TODATE = todate;
            ViewBag.ADD = Add;
            int Size_Of_Page = 50;
            int No_Of_Page = (Page_No ?? 1);
            DateTime FromDate = string.IsNullOrEmpty(fromdate) ? new DateTime() : DateTime.Parse(fromdate);
            DateTime ToDate = string.IsNullOrEmpty(todate) ? DateTime.Now : DateTime.Parse(todate);
            ToDate = ToDate.AddDays(1);
            IQueryable<TreoPhuon> result;
            var lstDVs = db.DvhcC1.Where(x => x.address_id == Add.Value).Select(x => x.id).ToArray();
            result = db.TreoPhuons.Where(x => x.NgayTreo >= FromDate &&
                      x.NgayTreo < ToDate);
            if (Add.HasValue)
                result = result.Where(x => lstDVs.Contains(x.DvhcC1_id));
            ViewBag.TONGSO = result.Count().ToString("N0");
            result = result.OrderByDescending(x => x.NgayTreo);
            return View(result.ToPagedList(No_Of_Page, Size_Of_Page));
        }

        // GET: TreoPhuons/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TreoPhuon treoPhuon = db.TreoPhuons.Find(id);
            if (treoPhuon == null)
            {
                return HttpNotFound();
            }
            return View(treoPhuon);
        }

        // GET: TreoPhuons/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TreoPhuons/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TreoPhuon treoPhuon, HttpPostedFileBase[] imgs)
        {
            if (ModelState.IsValid)
            {
                if (imgs.Length > 0)
                {
                    db.TreoPhuons.Add(treoPhuon);
                    var file = imgs[0];
                    if (file != null)
                    {
                        string filename = DateTime.Now.ToString("sshhmmddMMyy") + file.FileName;
                        file.SaveAs(Server.MapPath("~/public/phuon/") + filename);
                        treoPhuon.Images = "/public/phuon/" + filename;
                    }
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }

            return View(treoPhuon);
        }

        // GET: TreoPhuons/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TreoPhuon treoPhuon = db.TreoPhuons.Find(id);
            if (treoPhuon == null)
            {
                return HttpNotFound();
            }
            var dvhc = db.DvhcC1.Find(treoPhuon.DvhcC1_id);
            ViewBag.CAPXA = dvhc.address_id;
            return View(treoPhuon);
        }

        // POST: TreoPhuons/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TreoPhuon treoPhuon, HttpPostedFileBase[] imgs)
        {
            if (ModelState.IsValid)
            {
                var oldtreoPhuon = db.TreoPhuons.Find(treoPhuon.id);
                oldtreoPhuon.DvhcC1_id = treoPhuon.DvhcC1_id;
                oldtreoPhuon.GoogleMap = treoPhuon.GoogleMap;
                oldtreoPhuon.note = treoPhuon.note;
                oldtreoPhuon.NgayKiemTra = treoPhuon.NgayKiemTra;
                oldtreoPhuon.NgayTreo = treoPhuon.NgayTreo;

                if (imgs.Length > 0 && imgs[0] != null)
                {
                    var file = imgs[0];
                    if (file != null)
                    {
                        string filename = DateTime.Now.ToString("sshhmmddMMyy") + file.FileName;
                        file.SaveAs(Server.MapPath("~/public/phuon/") + filename);
                        oldtreoPhuon.Images = "/public/phuon/" + filename;
                    }
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(treoPhuon);
        }

        // GET: TreoPhuons/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TreoPhuon treoPhuon = db.TreoPhuons.Find(id);
            if (treoPhuon == null)
            {
                return HttpNotFound();
            }
            return View(treoPhuon);
        }

        // POST: TreoPhuons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TreoPhuon treoPhuon = db.TreoPhuons.Find(id);
            db.TreoPhuons.Remove(treoPhuon);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/TreoPhuons/Create.cshtml
@model NiceHandles.Models.TreoPhuon
@using NiceHandles.Models
@{
    ViewBag.Title = "Thêm mới";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var db = new NHModel();
}

<h2>Thêm mới</h2>

@using (Html.BeginForm("Create", "TreoPhuons", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Treo Phướn</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Hình ảnh", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("imgs", "", new { @class = "form-control", @type = "file" })
                @Html.ValidationMessageFor(model => model.Images, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Xã", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("capxa", new SelectList(db.Addresses.Select(x => new { id = x.id, name = x.name }), "id", "name"), new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Thôn", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.DvhcC1_id, new SelectList(db.DvhcC1.Select(x => new { id = x.id, name = x.name }), "id", "name"), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DvhcC1_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GoogleMap, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GoogleMap, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GoogleMap, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayTreo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayTreo, new { htmlAttributes = new { @class = "form-control datetime" } })
                @Html.ValidationMessageFor(model => model.NgayTreo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayKiemTra, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayKiemTra, new { htmlAttributes = new { @class = "form-control datetime" } })
                @Html.ValidationMessageFor(model => model.NgayKiemTra, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.note, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.note, new { @class = "form-control", @rows = 5 })
                @Html.ValidationMessageFor(model => model.note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm mới" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Về danh sách", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $(".datetime").datepicker({
                "autoclose": true,
                "todayHighlight": true,
                "dateFormat": "dd/mm/yyyy",
                "format": "dd/mm/yyyy",
            }).datepicker("setDate", new Date());
            $(function () {
                $.validator.methods.date = function (value, element) {
                    return this.optional(element) || moment(value, "DD/MM/YYYY", true).isValid();
                }
            });
            $("#capxa").change(function () {
                $.ajax({
                    url: '/CanBoDiaPhuongs/GetThon',
                    type: "GET",
                    dataType: "JSON",
                    data: { xa: $(this).val() },
                    success: function (thons) {
                        $("#DvhcC1_id").html(""); // clear before appending new list
                        $.each(thons, function (i, thon) {
                            $("#DvhcC1_id").append(
                                $('<option></option>').val(thon.id).html(thon.name));
                        });
                    }
                });
            });
            $("#capxa").trigger("change");
        });
    </script>
}

Views/TreoPhuons/Delete.cshtml
@model NiceHandles.Models.TreoPhuon

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TreoPhuon</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Images)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Images)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DvhcC1_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DvhcC1_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GoogleMap)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GoogleMap)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayTreo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayTreo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayKiemTra)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayKiemTra)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.note)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/TreoPhuons/Details.cshtml
@model NiceHandles.Models.TreoPhuon

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>TreoPhuon</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Images)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Images)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DvhcC1_id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DvhcC1_id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GoogleMap)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GoogleMap)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayTreo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayTreo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayKiemTra)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayKiemTra)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.note)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/TreoPhuons/Edit.cshtml
@model NiceHandles.Models.TreoPhuon
@using NiceHandles.Models
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var db = new NHModel();
}

<h2>Chỉnh sửa</h2>

@using (Html.BeginForm("Edit", "TreoPhuons", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Treo Phướn</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.Label("Hình ảnh", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBox("imgs", "", new { @class = "form-control", @type = "file" })
                <img height="100" width="100" src="@Model.Images" />
                @Html.ValidationMessageFor(model => model.Images, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Xã", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("capxa", new SelectList(db.Addresses.Select(x => new { id = x.id, name = x.name }), "id", "name", ViewBag.CAPXA), new { @class = "form-control" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Thôn", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.DvhcC1_id, new SelectList(db.DvhcC1.Select(x => new { id = x.id, name = x.name }), "id", "name"), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DvhcC1_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GoogleMap, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GoogleMap, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GoogleMap, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayTreo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayTreo, new { htmlAttributes = new { @class = "form-control datetime", Value = Model.NgayTreo.ToString("dd/MM/yyyy") } })
                @Html.ValidationMessageFor(model => model.NgayTreo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayKiemTra, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayKiemTra, new { htmlAttributes = new { @class = "form-control datetime", Value = Model.NgayKiemTra.HasValue ? Model.NgayKiemTra.Value.ToString("dd/MM/yyyy") : null } })
                @Html.ValidationMessageFor(model => model.NgayKiemTra, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.note, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.note, new { @class = "form-control", @rows = 5 })
                @Html.ValidationMessageFor(model => model.note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Về danh sách", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $(".datetime").datepicker({
                "autoclose": true,
                "todayHighlight": true,
                "dateFormat": "dd/mm/yyyy",
                "format": "dd/mm/yyyy",
            }).datepicker();
            $(function () {
                $.validator.methods.date = function (value, element) {
                    return this.optional(element) || moment(value, "DD/MM/YYYY", true).isValid();
                }
            });
            $("#capxa").change(function () {
                $.ajax({
                    url: '/CanBoDiaPhuongs/GetThon',
                    type: "GET",
                    dataType: "JSON",
                    data: { xa: $(this).val() },
                    success: function (thons) {
                        $("#DvhcC1_id").html(""); // clear before appending new list
                        $.each(thons, function (i, thon) {
                            $("#DvhcC1_id").append(
                                $('<option></option>').val(thon.id).html(thon.name));
                        });
                    }
                });
            });
        });
    </script>
}

Views/TreoPhuons/Index.cshtml
@model PagedList.IPagedList<NiceHandles.Models.TreoPhuon>
@using PagedList.Mvc;
@using NiceHandles.Models
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var db = new NHModel();
}

<h2>Danh sách treo phướn</h2>

<p>
    @Html.ActionLink("Thêm mới", "Create")
</p>
@using (Html.BeginForm("Index", "TreoPhuons", FormMethod.Get))
{
    <div class="row">
        <div class="col-sm-2">
            <div class="form-group">
                @Html.DropDownList("add", new SelectList(db.Addresses, "id", "name", ViewBag.ADD), "Xã, phường", new { @class = "form-control" })
            </div>
        </div>
        <div class="col-sm-1">
            <div class="form-group">
                @Html.TextBox("fromdate", ViewBag.FROMDATE as string, new { @class = "form-control datetime", placeholder = "Từ ngày", autocomplete = "off" })
            </div>
        </div>
        <div class="col-sm-1">
            <div class="form-group">
                @Html.TextBox("todate", ViewBag.TODATE as string, new { @class = "form-control datetime", placeholder = "Đến ngày", autocomplete = "off" })
            </div>
        </div>

        <div class="col-sm-1">
            <div class="form-group">
                <button type="submit" class="btn btn-danger fa fa-search" style="height: 32px; width: 100px;">Tìm kiếm</button>
            </div>
        </div>
    </div>
}
<strong style="float: right;">Tổng Số: @ViewBag.TONGSO</strong>
<table class="table">
    <tr>
        <th>
            Hình ảnh
        </th>
        <th>
            Địa chỉ
        </th>
        <th>
            GoogleMap
        </th>
        <th>
            Ngày treo
        </th>
        <th>
            Ngày kiểm tra
        </th>
        <th>
            Ghi chú
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        var dvhc = db.DvhcC1.Find(item.DvhcC1_id);
        var xa = db.Addresses.Find(dvhc.address_id);
        <tr>
            <td>
                <img height="100" width="100" src="@item.Images" />
            </td>
            <td>
                @Html.Raw(dvhc.name + ", " + xa.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GoogleMap)
            </td>
            <td>
                @item.NgayTreo.ToString("dd/MM/yyyy")
            </td>
            <td>
                @Html.Raw(item.NgayKiemTra.HasValue ? item.NgayKiemTra.Value.ToString("dd/MM/yyyy") : "")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.note)
            </td>
            <td>
                @Html.ActionLink("Chỉnh sửa", "Edit", new { id = item.id }) |
                @Html.ActionLink("Xóa", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>
@if (Model.PageCount > 1)
{
    <div class="row" style="margin-top: 10px;">
        <div class="col-sm-1">
            Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
        </div>
        <div class="col-sm-10">
            @Html.PagedListPager(Model, Page_No => Url.Action("Index", new { Page_No, Add = ViewBag.ADD, fromdate = ViewBag.FROMDATE, todate = ViewBag.TODATE }))
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $(".datetime").datepicker({
                "autoclose": true,
                "todayHighlight": true,
                "dateFormat": "dd/mm/yyyy",
                "format": "dd/mm/yyyy",
            }).datepicker();
        });
    </script>
}