Models/Contract.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.HoSoes = new HashSet<HoSo>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string name { get; set; }
        public int address_id { get; set; }
        public int service_id { get; set; }
        public long amount { get; set; }
        public long consuming { get; set; }
        public System.DateTime time { get; set; }
        public int time_exp { get; set; }
        public int deadline { get; set; }
        public int status { get; set; }
        public string note { get; set; }
        public int account_id { get; set; }
        public int Priority { get; set; }
        public int partner { get; set; }
        public string sodienthoai { get; set; }
        public string sodienthoai_mota { get; set; }
        public int type { get; set; }
        public int rose { get; set; }
        public int outrose { get; set; }
        public int dove { get; set; }
        public int remunerate { get; set; }
        public int soanthao { get; set; }
        public string HardFileLink { get; set; }
        public int loai { get; set; }
        public int nguoiky_id { get; set; }
        public int nguoitheodoi_id { get; set; }
        public string googlemap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoSo> HoSoes { get; set; }
    }
}

Models/Dove.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dove
    {
        public int id { get; set; }
        public int hoso_id { get; set; }
        public int status { get; set; }
        public System.DateTime time { get; set; }
        public string scan_bia { get; set; }
        public Nullable<System.DateTime> time_start { get; set; }
        public Nullable<System.DateTime> time_tradiem { get; set; }
        public Nullable<System.DateTime> time_vexong { get; set; }
        public Nullable<System.DateTime> time_dongdau { get; set; }
        public Nullable<System.DateTime> time_thamdinh { get; set; }
        public string note { get; set; }
        public int account_id { get; set; }
    }
}

Models/Page4.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiceHandles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page4
    {
        public int id { get; set; }
    }
}

Controllers/ContractsController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Core.Common.CommandTrees;
using System.IO;
using System.Linq;
using System.Net;
using System.Runtime.Caching;
using System.Runtime.ConstrainedExecution;
using System.Security.Cryptography;
using System.Security.Policy;
using System.Web;
using System.Web.Mvc;
using Aspose.Words;
using Aspose.Words.Rendering;
using Microsoft.AspNet.Identity;
using NiceHandles.Models;
using PagedList;
using PdfSharp.Charting;
using static System.Net.WebRequestMethods;

namespace NiceHandles.Controllers
{
    [Authorize(Roles = "SuperAdmin,Manager,Member")]
    public class ContractsController : Controller
    {
        private static readonly MemoryCache _cache = MemoryCache.Default;
        private NHModel db = new NHModel();

        // GET: Contracts        
        [Authorize(Roles = "SuperAdmin,Manager,Accounting")]
        public ActionResult Index(string Search_Data, int? add, int? acc, int? ser, int? par, int? loai, int? hh, string Filter_Value, int? Page_No, string fromdate, string todate)
        {
            if (Search_Data != null)
            {
                Page_No = 1;
            }
            else
            {
                Search_Data = Filter_Value;
            }
            ViewBag.FilterValue = Search_Data;
            ViewBag.ADD = add;
            ViewBag.SER = ser;
            ViewBag.LOAI = loai;
            ViewBag.PAR = par;
            ViewBag.ACC = acc;
            ViewBag.HH = hh;
            ViewBag.FROMDATE = fromdate;
            ViewBag.TODATE = todate;
            DateTime FromDate = string.IsNullOrEmpty(fromdate) ? new DateTime() : DateTime.Parse(fromdate);
            DateTime ToDate = string.IsNullOrEmpty(todate) ? DateTime.Now : DateTime.Parse(todate);
            ToDate = ToDate.AddDays(1);
            int[] partners = new int[0];
            if (hh.HasValue)
            {
                partners = db.Partners.Where(x => x.account_id == hh.Value).Select(x => x.id).ToArray();
            }
            var results = from io in db.vContracts
                          where (
                          (io.loai == (loai.HasValue ? loai.Value : io.loai)) &&
                          (io.partner == (par.HasValue ? par.Value : io.partner)) &&
                          (io.account_id == (acc.HasValue ? acc.Value : io.account_id)) &&
                          (io.address_id == (add.HasValue ? add : io.address_id)) &&
                          io.service_id == (ser.HasValue ? ser.Value : io.service_id) &&
                          (hh.HasValue ? partners.Contains(io.partner) : true) &&
                          io.time >= FromDate &&
                          io.time < ToDate &&
                          io.status < (int)XContract.eStatus.Cancel &&
                          io.name.ToUpper().Contains((!string.IsNullOrEmpty(Search_Data) ? Search_Data.ToUpper() : io.name.ToUpper())
                          ))
                          orderby io.time descending
                          select io;
            ViewBag.db = db;
            int Size_Of_Page = 30;
            int No_Of_Page = (Page_No ?? 1);
            //SUM
            //Đóng mở sumery
            //var cateRose = db.Categories.Single(x => x.kind == (int)XCategory.eKind.Rose);
            //var cateDove = db.Categories.Single(x => x.kind == (int)XCategory.eKind.Dove);
            //var cateRemunerate = db.Categories.Single(x => x.kind == (int)XCategory.eKind.Remunerate);
            //var catePartner = db.Categories.Single(x => x.kind == (int)XCategory.eKind.Partner);

            //var summery = results.Select(x => new { x.id, x.amount, x.consuming, x.dove, x.outrose, x.rose }).ToList();
            //var SumGiaTriHopDong = summery.Sum(x => x.amount);
            //var summeryInout = (from s in summery
            //                    join io in db.InOuts on s.id equals io.contract_id
            //                    where io.status == (int)XInOut.eStatus.DaThucHien
            //                    select new { io.amount, io.type, io.category_id }).ToList();
            //var SumDaThu = summeryInout.Where(x => x.type == (int)XCategory.eType.Thu).Sum(x => x.amount);
            //var SumPhaiThu = SumGiaTriHopDong - SumDaThu;
            //var SumDuChi = summery.Sum(x => x.consuming);
            //var SumHoaHongNV = summeryInout.Where(x => x.type == (int)XCategory.eType.Chi && x.category_id == cateRose.id).Sum(x => x.amount);
            //var SumHoaHongDT = summeryInout.Where(x => x.type == (int)XCategory.eType.Chi && x.category_id == catePartner.id).Sum(x => x.amount);
            //var SumDaChi = summeryInout.Where(x => x.type == (int)XCategory.eType.Chi).Sum(x => x.amount);
            //var SumDaThuNet = SumDaThu - SumDaChi;
            //var SumDuThuNet = SumGiaTriHopDong - SumDuChi;

            //ViewBag.SumGiaTriHopDong = SumGiaTriHopDong;
            //ViewBag.SumDaThu = SumDaThu;
            //ViewBag.SumPhaiThu = SumPhaiThu;
            //ViewBag.SumDuChi = SumDuChi;
            //ViewBag.SumHoaHongNV = SumHoaHongNV;
            //ViewBag.SumHoaHongDT = SumHoaHongDT;
            //ViewBag.SumDaChi = SumDaChi;
            //ViewBag.SumDaThuNet = SumDaThuNet;
            //ViewBag.SumDuThuNet = SumDuThuNet;

            return View(results.ToPagedList(No_Of_Page, Size_Of_Page));
        }

        [Authorize(Roles = "SuperAdmin,Manager,Accounting")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contract contract = db.Contracts.Find(id);
            if (contract == null)
            {
                return HttpNotFound();
            }
            return View(contract);
        }

        [Authorize(Roles = "SuperAdmin,Manager,Accounting")]
        // GET: Contracts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Contracts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "SuperAdmin,Accounting")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create(XContract obj)
        {
            obj.hoso.name = obj.contract.name;
            obj.hoso.account_id = obj.contract.account_id;
            var contract = obj.contract;
            var hoso = obj.hoso;
            if (ModelState.IsValid)
            {
                var username = User.Identity.GetUserName();
                var acc = db.Accounts.Where(x => x.UserName.Equals(username)).Single();

                contract.name = Utils.RemoveSpecialCharactor(contract.name);
                contract.status = (int)XContract.eStatus.Processing;
                contract.time = DateTime.Now;
                db.Contracts.Add(contract);
                db.SaveChanges();
                wf_contract wf = new wf_contract();

                wf.account_id = acc.id;
                wf.contract_id = contract.id;
                wf.note = "Khởi tạo";
                wf.status = (int)Xwf_contract.eStatus.Processing;
                wf.time = DateTime.Now;
                db.wf_contract.Add(wf);
                // Hồ sơ                                
                hoso.account_id_soanthao = contract.soanthao;
                hoso.contract_id = contract.id;
                //hoso.note = contract.note;
                hoso.priority = contract.Priority;
                hoso.service_id = contract.service_id;
                hoso.status = contract.status;
                hoso.time_created = contract.time;
                hoso.trang4 = contract.type;
                hoso.step_id = db.Steps.OrderBy(x => x.sort).First().id;
                db.HoSoes.Add(hoso);
                db.SaveChanges();
                NHTrans.SaveLog(db, acc.id, "Hệ thống", "Tự động thêm mới hồ sơ " + hoso.name);

                // Tạo lịch nhắc nhớ ////////////////////////////////////////////////////////
                //1, Nhiệm vụ                
                var nhiemvu = XViecPhaiLam.CreateModel(hoso.id, acc.id, (int)XProgress.eType.NhiemVu, 2);
                db.ViecPhaiLams.Add(nhiemvu);
                //2, Điều tra
                var dieutra = XViecPhaiLam.CreateModel(hoso.id, acc.id, (int)XProgress.eType.DieuTra, 7);
                db.ViecPhaiLams.Add(dieutra);
                //3, Gia phả
                var giapha = XViecPhaiLam.CreateModel(hoso.id, acc.id, (int)XProgress.eType.GiaPha, 7);
                db.ViecPhaiLams.Add(giapha);
                //4, Điều tra
                var banve = XViecPhaiLam.CreateModel(hoso.id, acc.id, (int)XProgress.eType.BanVe, 7);
                db.ViecPhaiLams.Add(banve);
                //5, Hộ tịch
                var hotich = XViecPhaiLam.CreateModel(hoso.id, acc.id, (int)XProgress.eType.GiayToHoTich, 7);
                db.ViecPhaiLams.Add(hotich);
                //6, Giấy tờ xã
                var gtxa = XViecPhaiLam.CreateModel(hoso.id, acc.id, (int)XProgress.eType.GiayToXa, 7);
                db.ViecPhaiLams.Add(gtxa);
                ////////////////////////////END////////////////////////////////////////////
                // Hồ sơ                                
                var infomation = new Infomation();
                infomation.hoso_id = hoso.id;
                infomation.contract_id = contract.id;
                db.Infomations.Add(infomation);
                db.SaveChanges();

                // 
                if (obj.HardFileLinks.Count > 0)
                {
                    var file = obj.HardFileLinks[0];
                    if (file != null)
                    {

Controllers/DoveController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Principal;
using System.Web;
using System.Web.Mvc;
using System.Web.Razor.Parser.SyntaxTree;
using NiceHandles.Models;
using PagedList;

namespace NiceHandles.Controllers
{
    [Authorize(Roles = "SuperAdmin,Manager,Member,OutSide")]
    public class DoveController : Controller
    {
        private NHModel db = new NHModel();

        // GET: NhiemVus        
        public ActionResult Index(string Search_Data, string Filter_Value, int? Page_No)
        {
            if (Search_Data != null)
            {
                Page_No = 1;
            }
            else
            {
                Search_Data = Filter_Value;
            }
            ViewBag.FilterValue = Search_Data;

            var steps = db.Steps.Where(x => x.category_id != (int)XStep.ePhong.HSLuu).Select(x => x.id).ToArray();
            //var steps = db.Steps.Where(x => x.category_id == (int)XStep.ePhong.DoVe).Select(x => x.id).ToArray();

            var results = from io in db.DSBanLamViecs
                          join s in steps on io.step equals s
                          where
                               io.customer_name.ToUpper().Contains(!string.IsNullOrEmpty(Search_Data) ? Search_Data.ToUpper() : io.customer_name.ToUpper())
                          orderby io.Priority descending, io.time descending
                          select io;
            int Size_Of_Page = 150;
            int No_Of_Page = (Page_No ?? 1);
            return View(results.ToPagedList(No_Of_Page, Size_Of_Page));
        }
        public ActionResult Dove(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var nv = db.NhiemVus.Where(x => x.contract_id == id).FirstOrDefault();
            if (nv == null)
            {
                nv = new NhiemVu();
                nv.step_id = db.Steps.First().id;
                nv.contract_id = id.Value;
                db.NhiemVus.Add(nv);
                db.SaveChanges();
            }
            var contract = db.Contracts.Find(id);                        
            var address = db.Addresses.Find(contract.address_id);
            ViewBag.Address = address;
            ViewBag.Contract = contract;
            //var sid = db.fk_contract_service.Where(x => x.contract_id == id).First().service_id;
            var service = db.Services.Find(contract.service_id);
            ViewBag.Service = service;
            var fs = db.Files.Where(x => x.contract_id == id);
            Dictionary<int, string> FILES = new Dictionary<int, string>();
            foreach (var per in XFile.sType)
            {
                string temp = string.Empty;
                foreach (var item in fs.Where(x => x.type == per.Key))
                {
                    temp += "<a href='" + item.url + "' target='_blank' >" + item.name + "</a><span id='" + item.id + "' class='del'>x</span> | ";
                }
                FILES.Add(per.Key, temp);
            }
            ViewBag.FILES = FILES;
            return View(nv);
        }        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Contracts/BanLamViec_BAK.cshtml
@model PagedList.IPagedList<NiceHandles.Models.DSBanLamViec>
@using PagedList.Mvc;
@using NiceHandles.Models

@{
    ViewBag.Title = "Bàn làm việc";
    var db = (NiceHandles.Models.NHModel)ViewBag.db;
    var accounts = db.Accounts.Where(x => x.hasNote == (int)XModels.eYesNo.Yes).ToArray();
}


<link href="~/Content/Jobs.css" rel="stylesheet" />

<h2>NHIỆM VỤ</h2>
@*<button type="button" class="btn btn-info" onclick="Print();">Bản in tổng</button> &nbsp;*@
<p style="text-align: right;">
    @*<button type="button" class="btn btn-info" onclick="Go();">Đi 1 cửa</button>&nbsp;*@
    @*<button type="button" class="btn btn-primary" onclick="GoDiaChinh();">DS nộp xã</button>&nbsp;*@
    <button type="button" class="btn btn-primary" onclick="GoGiayTo();">DS giao nhận giấy tờ</button>&nbsp;
    <button type="button" class="btn btn-info" onclick="AlreadyGo();">DS đi 1 cửa</button>&nbsp;
</p>

<div class="row">
    @foreach (var acc in accounts)
    {
        <div class="col-sm-3">
            <h4>@acc.fullname.ToUpper()<button onclick="Print(@acc.id);" class="btn btn-info" style="float: right;">In</button></h4>
            <a onclick="btnNew_click(@acc.id)">Thêm việc mới</a>
            <div class="form-group">
                <ul id="@( "myUL" + acc.id)" class="ulb">
                    @foreach (var item in db.Jobs.Where(x => x.process_by == acc.id).OrderBy(x => x.status))
                    {
                        var lstT = db.tasks.Where(x => x.job_id == item.id).OrderBy(x => x.status);
                        var ca = db.tasks.Where(x => x.job_id == item.id).Count();
                        var cf = db.tasks.Where(x => x.job_id == item.id && x.status == (int)XJob.eStatus.Complete).Count();

                        <li id="@Html.Raw("j" + item.id)">
                            <span class="caret">@Html.Raw(item.name + "(" + cf + "/" + ca + ")") </span><a class="edit" onclick='DelJob_Click(@item.id);'>X</a>
                            <ul class="nested">
                                <li><a onclick='AddTask_Click(this);'>Thêm nhiệm vụ</a>&nbsp;|&nbsp; <a onclick='EditTask_Click(this);'>Xóa</a></li>
                                @foreach (var t in lstT)
                                {
                                    <li>
                                        <input type="checkbox" class="task" id="@t.id" @Html.Raw(t.status == (int)XJob.eStatus.Complete ? "checked" : "") />@t.name
                                        <a class="edit" onclick='DelTask_Click(@t.id);'>X</a>
                                    </li>
                                }
                            </ul>
                        </li>
                    }
                </ul>
            </div>
        </div>
    }
</div>

<div class="modal" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" style="font-size: 16px; color: deeppink; text-align: center;">ĐI 1 CỬA</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-12">

                        <div class="form-horizontal">
                            <div class="form-group">
                                <label class="control-label col-md-2">Hợp đồng</label>
                                <div class="col-md-10">
                                    <select id="cboHopDong" class="form-control"></select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-2">Ngày nộp</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control datetime" id="txtNgayNop" />
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-2">Ngày trả KQ</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control datetime" id="txtNgayTraKQ" />
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-2">Cán bộ 1 cửa</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" id="txtCanBo1Cua" />
                                </div>
                            </div>

                            @*<div class="form-group">
                                    <label class="control-label col-md-2">Cán bộ phụ trách</label>
                                    <div class="col-md-10">
                                        <input type="text" class="form-control" id="txtCanBoPhuTrach" />
                                    </div>
                                </div>*@

                            <div class="form-group">
                                <label class="control-label col-md-2">Mã phiếu hẹn</label>
                                <div class="col-md-10">
                                    <input type="text" class="form-control" id="txtMaPhieuHen" />
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" onclick="OnGo();">Nộp 1 cửa</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Hủy</button>
            </div>
        </div>
    </div>
</div>



<h2>Bàn làm việc</h2>

@using (Html.BeginForm("BanLamViec", "Contracts", FormMethod.Get))
{
    <div class="row">
        <div class="col-sm-2">
            <div class="form-group">
                @Html.TextBox("Search_Data", ViewBag.FilterValue as string, new { @class = "form-control", placeholder = "Tìm kiếm" })
            </div>
        </div>
        <div class="col-sm-2">
            <div class="form-group">
                @Html.DropDownList("ste", ViewBag.STEPS as SelectList, "--- Bước thực hiện ---", new { @class = "form-control", title = "Bước thực hiện" })
            </div>
        </div>
        <div class="col-sm-2">
            <div class="form-group">
                @Html.DropDownList("add", ViewBag.ADDRESS as SelectList, "--- Địa chỉ ---", new { @class = "form-control", title = "Địa chỉ" })
            </div>
        </div>
        <div class="col-sm-2">
            <div class="form-group">
                @Html.DropDownList("ser", ViewBag.SERVICES as SelectList, "--- Dịch vụ ---", new { @class = "form-control", title = "Dịch vụ" })
            </div>
        </div>
        <div class="col-sm-2">
            <div class="form-group">
                @Html.DropDownList("par", ViewBag.PARTNER as SelectList, "--- Đối tác ---", new { @class = "form-control", title = "Đối tác" })
            </div>
        </div>
        <div class="col-lg-2">
            <div class="form-group">
                <button type="submit" class="btn btn-danger" style="height: 32px; width: 100px;">Tìm kiếm</button>
            </div>
        </div>
    </div>
}
<table class="table table-hover" id="blv">
    <thead>
        <tr>
            <th style="width: 25%;">
                Tên khách hàng
            </th>
            <th>
                Đối tác
            </th>
            <th>
                Số điện thoại
            </th>
            <th>
                Địa chỉ
            </th>
            <th>
                Dịch vụ
            </th>
            <th>
                Bước thực hiện
            </th>
            <th>
                Gia phả
            </th>
            <th>
                Nhập thông Tin
            </th>
            <th>
                Ngày nhận
            </th>
            @*<th>
                    Ngày hạn
                </th>*@
            <th>
                Ưu tiên
            </th>
            @*<th>
                </th>*@
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            var href = string.Empty;
            var nguoithuchien = string.Empty;
            //switch (item.step_code)
            //{
            //    case "NOP1CUA":
            //        var odi1cua = db.di1cua.Where(x => x.contract_id == item.id).SingleOrDefault();
            //        if (odi1cua == null)
            //        {
            //            odi1cua = new di1cua();
            //            odi1cua.contract_id = item.id;
            //            odi1cua.ngaynop = DateTime.Now;
            //            odi1cua.trangthai = (int)Xdi1cua.eStatus.ChoNop;
            //            odi1cua.ngaytra = DateTime.Now.AddDays(30);
            //            var canbo = db.CanBoes.Where(x => x.motcua == (int)XModels.eYesNo.Yes).FirstOrDefault();
            //            odi1cua.canbo1cua = canbo != null ? canbo.id : db.CanBoes.First().id;
            //            db.di1cua.Add(odi1cua);
            //        }
            //        href = "<a href='/di1cua/Edit/" + odi1cua.id + "'>" + item.customer_name + "</a>";
            //        break;
            //    default:
            //        href = "<a href='/NhiemVus/?id=" + item.id + "&step=" + item.step + "'>" + item.customer_name + "</a>";
            //        break;
            //}
            href = "<a href='/NhiemVus/?id=" + item.id + "&step=" + item.step + "'>" + item.customer_name + "</a>";
            nguoithuchien = item.account_id.HasValue ?
            item.account_name + "<a href='/contracts/cancelassign/?id=" + item.id + "' style='color: red; vertical-align: 2px; padding-left: 5px;'>x</a>" :
            "<a href='/contracts/assign/?id=" + item.id + "' class='text-success'>Nhận việc</a>";
            <tr>
                <td>
                    @Html.Raw(href)
                    <a href='/Infomations/Edit?contract_id=@item.id' class="h"> - Nhập thông tin</a>
                </td>
                <td>
                    @item.partner_name
                </td>
                <td>
                    @item.sodienthoai
                </td>
                <td>
                    @item.address_name
                </td>
                <td>
                    @item.service_name
                </td>
                <td style="color: @item.step_color">
                    @item.step_name
                </td>
                <td>
                    @if (item.hasfile.HasValue)
                    {
                        @Html.ActionLink("Xem", "GiaPha", "Home", new { c = item.id }, new { @class = "fa-solid fa-eye" })
                    }
                    else
                    {
                        <i>---</i>
                    }

                </td>
                <td>
                    @Html.Raw(nguoithuchien)
                </td>
                <td>
                    @item.time.ToString("dd/MM/yyyy")
                </td>
                @*<td>
                        @if (item.obj.exp.HasValue)
                        {
                            if (item.obj.exp.Value < DateTime.Now && item.obj.status == (int)Xwf_contract.eStatus.Processing)
                            {
                                <i style="color: red">
                                    @item.obj.exp.Value.ToString("dd/MM/yyyy")
                                </i>
                            }
                            else
                            {
                                @item.obj.exp.Value.ToString("dd/MM/yyyy")
                            }
                        }
                    </td>*@
                <td>
                    @XContract.sPriority[item.Priority]
                </td>
                @*<td>
                        @if (item.obj.status == (int)XContract.eStatus.Processing)
                        {
                            @Html.ActionLink("Bước tiếp", "Next", "Contracts", new { id = item.obj.id }, new { style = "background-color:aliceblue;color:#337ab7;" })
                            @Html.Raw(" |")
                            @Html.ActionLink("Trả về", "Prev", "Contracts", new { id = item.obj.id }, new { style = "background-color:aliceblue;color:deeppink;" })
                        }
                    </td>*@
            </tr>
        }
    </tbody>
</table>
@if (Model.PageCount > 1)
{
    <div class="row" style="margin-top: 10px;">
        <div class="col-sm-1">
            Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
        </div>
        <div class="col-sm-10">
            @Html.PagedListPager(Model, Page_No => Url.Action("BanLamViec", new { Page_No, Filter_Value = ViewBag.FilterValue, add = ViewBag.ADD, ser = ViewBag.SER, par = ViewBag.PAR, ste = ViewBag.STEP }))
        </div>
    </div>
}


<iframe id="my_iframe" style="display:none;"></iframe>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/Jobs.js"></script>

}

Views/Contracts/_ModalCreateDuyetChi.cshtml
<div id="mdlCreateDuyetChi" class="modal" role="dialog" tabindex="-1">
    <div class="modal-dialog modal-lg" role="document" style="width:80%">
        <div class="modal-content">
            <div class="modal-body">
                <iframe src="" height="600px" width="100%" style="padding: 20px; border: none;"></iframe>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng lại</button>
            </div>
        </div>
    </div>
</div> 